accounts/urls.py
from django.urls import path
from .views import *

app_name = 'accounts'

urlpatterns = [
	path('login', login, name= 'login'),
	path('register', register, name= 'register'),
	path('logout', logout, name= 'logout'),
	path('dashboard', dashboard, name= 'dashboard'),
	path('editprofile', editprofile, name= 'editprofile'),
]

carts/urls.py
from django.urls import path
from . import views

app_name = 'carts'

urlpatterns = [
	path('add/<int:listing>', views.add, name= 'add'),
	path('delete/<int:listing>', views.delete, name= 'delete'),
] 

listings/urls.py
from django.urls import path
from . import views

app_name = 'listings'

urlpatterns = [
	path('', views.index, name= 'listings'),
	path('<int:listing_id>', views.listing, name= 'listing'),
	path('search', views.search, name= 'search'),
	path('add', views.add, name= 'add'),
]

pages/urls.py
from django.urls import path
from .views import *

app_name = 'pages'

urlpatterns = [
	path('', index, name='index'),
	path('about', about, name='about'),
	
]

rest/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    path('', include('pages.urls')),
    path('listings/', include('listings.urls')),
    path('accounts/', include('accounts.urls')),
    path('contacts/', include('contacts.urls')),
    path('carts/', include('carts.urls')),
    path('wishlists/', include('wishlists.urls')),
    path('admin/', admin.site.urls),
] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)
 

wishlists/urls.py
from django.urls import path
from . import views

app_name = 'wishlists'

urlpatterns = [
	path('add/<int:listing>', views.add, name= 'add'),
	path('delete/<int:listing>', views.delete, name= 'delete'),
] 

accounts/models.py
from django.db import models

# Create your models here.

accounts/views.py
from django.shortcuts import render, redirect
from django.contrib import messages, auth
from django.contrib.auth.models import User
from contacts.models import Contact
from carts.models import Cart
from wishlists.models import Wishlist

from django.contrib.auth.hashers import make_password

# Create your views here.

def login(request):
	if request.method == 'POST':
		username = request.POST['username']
		password = request.POST['password']
		user = auth.authenticate(username= username, password= password)
		if user:
			auth.login(request, user)
			messages.success(request, 'You are now logged in.')
			return redirect('accounts:dashboard')
		else:
			messages.error(request, 'Invalid Credentials.')
			return redirect('accounts:login')
	else:
		return render(request, 'accounts/login.html')

def register(request):
	if request.method == 'POST':
		data = {
			'first_name': request.POST['first_name'],
			'last_name': request.POST['last_name'],
			'username': request.POST['username'],
			'email': request.POST['email'],
			'password': request.POST['password'],
			'password2': request.POST['password2'],
		}
		# Simple validation for password
		if data['password'] == data['password2']:
			# Simple validation for username
			if User.objects.filter(username= data['username']).exists():
				messages.error(request, 'Username is exists.')
				return redirect('accounts:register')
			else:
				# Simple validation for username
				if User.objects.filter(email= data['email']).exists():
					messages.error(request, 'Email is exists.')
					return redirect('accounts:register')
				else:
					user = User.objects.create_user(
						first_name= data['first_name'],
						last_name= data['last_name'],
						username= data['username'],
						email= data['email'],
						password= data['password'],
						)
					user.save()
					messages.success(request, 'Successfully registered, Login here.')
					return redirect('accounts:login')

		else:
			messages.error(request, 'Two passwords must matches.')
			return redirect('accounts:register')
	else:
		return render(request, 'accounts/register.html')


def logout(request):
	if request.method == 'POST':
		auth.logout(request)
		messages.success(request, 'Successfully logged out.')
		return redirect('pages:index')


def dashboard(request):
	contacts = Contact.objects.order_by('-contact_date').filter(user_id= request.user.id)
	carts = Cart.objects.all().filter(user_id= request.user.id)
	wishlists = Wishlist.objects.order_by('-date').filter(user_id= request.user.id)
	context = {
		'contacts': contacts,
		'carts': carts,
		'wishlists': wishlists
	}
	return render(request, 'accounts/dashboard.html', context)

def editprofile(request):
	if request.user.is_authenticated:
		if request.method == 'GET':
			return render(request, 'accounts/editprofile.html')
		else:
			username = request.POST['username']
			email = request.POST['email']
			first_name = request.POST['first_name']
			last_name = request.POST['last_name']
			password1 = request.POST['password1']
			password2 = request.POST['password2']

			if password1 == password2:
				request.user.username = username
				request.user.email = email
				request.user.first_name = first_name
				request.user.last_name = last_name
				if password1 == '' and password2 == '':
					pass
				else:
					request.user.password = make_password(password1)
				request.user.save()
				messages.success(request, 'Profile Edited Successfully.')
				return redirect('accounts:editprofile')
			else:
				messages.error(request, 'Password and Password Confirmation must be the same.')
				return redirect('accounts:editprofile')
	else:
		messages.error(request, 'You have to login.')
		return redirect('accounts:login')



	

templates/accounts/dashboard.html
{% extends 'base.html' %}
{% block title %}User Dashboard {% endblock %}
{% block content %}
  <section id="showcase-inner" class="py-5 text-white">
    <div class="container">
      <div class="row text-center">
        <div class="col-md-12">
          <h1 class="display-4">User Dashboard</h1>
          <p class="lead">Manage your BT Real Estate account</p>
        </div>
      </div>
    </div>
  </section>
  <br>
  {% include 'partials/_alert.html' %}

  <!-- Breadcrumb -->
  <section id="bc" class="mt-3">
    <div class="container">
      <nav aria-label="breadcrumb">
        <ol class="breadcrumb">
          <li class="breadcrumb-item">
            <a href="{% url 'pages:index' %}">
              <i class="fas fa-home"></i> Home</a>
          </li>
          <li class="breadcrumb-item active"> Dashboard</li>
        </ol>
      </nav>
    </div>
  </section>

  <section id="dashboard" class="py-4">
    <div class="container">
      <div class="row">
        <div class="col-md-6">
          <h2>Welcome {{ user.first_name }}</h2>
          {% if contacts %}
            <p>Here are the property listings that you have inquired about</p>
            <table class="table">
              <thead>
                <tr>
                  <th scope="col">#</th>
                  <th scope="col">Property</th>
                  <th></th>
                </tr>
              </thead>
              <tbody>
                {% for contact in contacts %}                
                  <tr>
                    <td>{{ contact.listing_id }}</td>
                    <td>{{ contact.listing_title }}</td>
                    <td>
                      <a class="btn btn-light" href="{% url 'listings:listing' contact.listing_id %}">View Listing</a>
                    </td>
                  </tr>
                {% endfor %}
              </tbody>
            </table>
          {% else %}
          <h2>You have not make any Inqueries yet.</h2>
          {% endif %}
        </div>
        
        <div class="col-md-3">
          <div class="card mb-3">
            <div class="card-body">
              <h4 class="card-title">Cart <i class="text-secondary fas fa-shopping-cart"></i></h4>
              {% if carts %}
                {% for cart in carts %}
                  <a href="{% url 'listings:listing' cart.listing.id %}" class="text-secondary">{{ cart.listing }}</a>
                  <a href="{% url 'carts:delete' cart.listing.id %}" class="text-danger" style="float: right;"><i class="fas fa-trash"></i> Delete</a><br>
                {% endfor %}
              {% else %}
                <h6 class="card-title">Cart is empty</h6>
              {% endif %}
            </div>
          </div>
        </div>

        <div class="col-md-3">
          <div class="card mb-3">
            <div class="card-body">
              <h4 class="card-title">Wishlists <i class="text-secondary fas fa-heart"></i></h4>
              {% if wishlists %}
                {% for wishlist in wishlists %}
                  <a href="{% url 'listings:listing' wishlist.listing.id %}" class="text-secondary">{{ wishlist.listing }}</a>
                  <a href="{% url 'wishlists:delete' wishlist.listing.id %}" class="text-danger" style="float: right;"><i class="fas fa-trash"></i> Delete</a><br>
                {% endfor %}
              {% else %}
                <h6 class="card-title">Wishlists is empty</h6>
              {% endif %}
            </div>
          </div>
        </div>
      </div>
    </div>
  </section>
{% endblock %}

templates/accounts/editprofile.html
{% extends 'base.html' %}
{% block title %}User Dashboard - Edit Profile{% endblock %}
{% block content %}
  

  <!-- Breadcrumb -->
  <section id="bc" class="mt-3">
    <div class="container">
      <nav aria-label="breadcrumb">
        <ol class="breadcrumb">
          <li class="breadcrumb-item">
            <a href="{% url 'pages:index' %}">
              <i class="fas fa-home"></i> Home</a>
          </li>
          <li class="breadcrumb-item">
            <a href="{% url 'accounts:dashboard' %}">Dashboard</a>
          </li>
          <li class="breadcrumb-item active"> Edit Profile</li>
        </ol>
      </nav>
    </div>
  </section>

  <section id="dashboard" class="py-4">
    <div class="container">
      {% include 'partials/_alert.html' %}
      <div class="row">
        <div class="col-md-6">
          <h2>Welcome {{ user.first_name }}</h2>
        </div>
      </div>
      <div class="search">
        <form action="{% url 'accounts:editprofile' %}" method="POST">
          {% csrf_token %}
          <!-- Form Row 1 -->
         <div class="form-row">
            <div class="col-md-6 mb-3">
              <label>Username</label>
              <input type="text" name="username" class="form-control" required placeholder="Username" value="{{ user.username }}">
            </div>
            <div class="col-md-6 mb-3">
              <label>Email Address</label>
              <input type="email" name="email" class="form-control" required placeholder="Email" value="{{ user.email }}">
            </div>
          </div>
          <div class="form-row">
            <div class="col-md-6 mb-3">
              <label>Password</label>
              <input type="password" name="password1" class="form-control" placeholder="Password">
            </div>
            <div class="col-md-6 mb-3">
              <label>Password Confirmation</label>
              <input type="password" name="password2" class="form-control" placeholder="Password Confirmation">
            </div>
          </div>
          <div class="form-row">
            <div class="col-md-6 mb-3">
              <label>First Name</label>
              <input type="text" name="first_name" class="form-control" required placeholder="First Name" value="{{ user.first_name }}">
            </div>

            <div class="col-md-6 mb-3">
              <label>Last Name</label>
              <input type="text" name="last_name" class="form-control" required placeholder="Last Name" value="{{ user.last_name }}">
            </div>           
          </div>
          <button class="btn btn-secondary btn-block mt-4" type="submit">Edit Profile</button>
        </form>
      </div>
    </div>
  </section>
{% endblock %}

templates/accounts/login.html
{% extends 'base.html' %}
{% block content %}
	<section id="login" class="bg-light py-5">
		<div class="container">
		  <div class="row">
		    <div class="col-md-6 mx-auto">
		      <div class="card">
		        <div class="card-header bg-primary text-white">
		          <h4>
		            <i class="fas fa-sign-in-alt"></i> Login</h4>
		        </div>
		        <div class="card-body">
		        	{% include 'partials/_alert.html' %}
		        	<form action="{% url 'accounts:login'%}" method="POST">
		            	{% csrf_token %}
			            <div class="form-group">
			              <label for="username">Username</label>
			              <input type="text" name="username" class="form-control" required>
			            </div>

			            <div class="form-group">
			              <label for="password2">Password</label>
			              <input type="password" name="password" class="form-control" required>
			            </div>

			            <input type="submit" value="Login" class="btn btn-secondary btn-block">
		            </form>
		        </div>
		      </div>
		    </div>
		  </div>
		</div>
	</section>

{% endblock %}

templates/accounts/register.html
{% extends 'base.html' %}
{% block content %}
	<section id="register" class="bg-light py-5">
		<div class="container">
		  <div class="row">
		    <div class="col-md-6 mx-auto">
		      <div class="card">
		        <div class="card-header bg-primary text-white">
		          <h4>
		            <i class="fas fa-user-plus"></i> Register</h4>
		        </div>
		        <div class="card-body">
					{% include 'partials/_alert.html' %}
		            <form action="{% url 'accounts:register'%}" method="POST">
		            	{% csrf_token %}
		                <div class="form-group">
			              <label for="first_name">First Name</label>
			              <input type="text" name="first_name" class="form-control" required>
			            </div>
			            <div class="form-group">
			              <label for="last_name">Last Name</label>
			              <input type="text" name="last_name" class="form-control" required>
			            </div>
			            <div class="form-group">
			              <label for="username">Username</label>
			              <input type="text" name="username" class="form-control" required>
			            </div>
			            <div class="form-group">
			              <label for="email">Email</label>
			              <input type="email" name="email" class="form-control" required>
			            </div>
			            <div class="form-group">
			              <label for="password2">Password</label>
			              <input type="password" name="password" class="form-control" required>
			            </div>
			            <div class="form-group">
			              <label for="password">Confirm Password</label>
			              <input type="password" name="password2" class="form-control" required>
			            </div>
			            <input type="submit" value="Register" class="btn btn-secondary btn-block">
			          </form>
		        	
		        </div>
		      </div>
		    </div>
		  </div>
		</div>
	</section>
	
{% endblock %}